REQUIRE_DIRECTIVE = "#require"

COMMENT_SYM = '\\'
NEWLINE_SYM = '\n'
ZERO_SYM = '0'
X_SYM = 'x'
DEFINITION_START_SYM = ':'
DEFINITION_END_SYM = ';'
SIGNATURE_START_SYM = '('
SIGNATURE_END_SYM = ')'
DOT_SYM = '.'
UNDERSCORE_SYM = '_'
STRING_QUOTE = "\""

HEX_DIGITS = 'abcdef'