REQUIRE_DIRECTIVE = "#require"

COMMENT_SYMBOL = '\\'
NEWLINE_SYMBOL = '\n'
ZERO_SYMBOL = '0'
X_SYMBOL = 'x'
DEFINITION_START_SYMBOL = ':'
DEFINITION_END_SYMBOL = ';'
SIGNATURE_START_SYMBOL = '('
SIGNATURE_END_SYMBOL = ')'
DOT_SYMBOL = '.'

HEX_DIGITS = 'abcdef'
